version: v1alpha1
debug: false
persist: true
machine:
    type: controlplane
    token: 69hay4.vz3q31hlhhp0yjj8
    ca:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJQekNCOHFBREFnRUNBaEVBeHJ5aW9DbVZvck9hc29IVTJTMEt3ekFGQmdNclpYQXdFREVPTUF3R0ExVUUKQ2hNRmRHRnNiM013SGhjTk1qWXdNVEU0TURFeE5qVTJXaGNOTXpZd01URTJNREV4TmpVMldqQVFNUTR3REFZRApWUVFLRXdWMFlXeHZjekFxTUFVR0F5dGxjQU1oQUVHODVla0s0ZXFkWXRxZUZhTlZLZ1gySVd0S2UvS01sNjduCkp3cFNSZzVObzJFd1h6QU9CZ05WSFE4QkFmOEVCQU1DQW9Rd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUcKQ0NzR0FRVUZCd01DTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkJnL3MyOXNyRHZBU3RJSQp1cnNoZFZoTTI3T0tNQVVHQXl0bGNBTkJBRnJKRWdVazRHVnB2OVVZY2hqS2gyMUxrREJjTUVwWHBIN1phbUJKCmdXclFUQmlWSkd6UTRMTTlZTlhKRXV6cWlIOEFIODdUanlYRFpxVElON3AyWUEwPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        key: LS0tLS1CRUdJTiBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0KTUM0Q0FRQXdCUVlESzJWd0JDSUVJSnhqYUF2S3ZJR3p6NnpqS1V6QlQ3WGVVRHc0aWVCcmYzYXJVaElzV2pORAotLS0tLUVORCBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0K
    certSANs: []
    kubelet:
        image: ghcr.io/siderolabs/kubelet:v1.35.0
        defaultRuntimeSeccompProfileEnabled: true
        disableManifestsDirectory: true
    network: {}
    install:
        disk: /dev/sda
        image: factory.talos.dev/nocloud-installer/88d1f7a5c4f1d3aba7df787c448c1d3d008ed29cfb34af53fa0df4336a56040b:v1.12.1
        wipe: false
        grubUseUKICmdline: true
    features:
        diskQuotaSupport: true
        kubePrism:
            enabled: true
            port: 7445
        hostDNS:
            enabled: true
            forwardKubeDNSToHost: true
    nodeLabels:
        node.kubernetes.io/exclude-from-external-load-balancers: ""
cluster:
    id: yZrFB-2LBUkVB6V03jURZMGckTfdW39luck7T5rKe6o=
    secret: 78kQPdsm6udNybmyJr22HpDn8e3AJH0io4K05mlnPuI=
    controlPlane:
        endpoint: https://k8s.internal.salesulhoa.com:6443
    clusterName: talos
    network:
        dnsDomain: k8s.internal.salesulhoa.com
        podSubnets:
            - 10.244.0.0/16
        serviceSubnets:
            - 10.96.0.0/12
    token: hjntvk.kc37ht5aib38aves
    secretboxEncryptionSecret: /PDWKqYvV+rXNQ0TxijHS8CPyDFAhOvPcs6OU4iV1Eo=
    ca:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpVENDQVMrZ0F3SUJBZ0lRUVI1ZHVQZHBJS3RtRE1GNmdUaVlyVEFLQmdncWhrak9QUVFEQWpBVk1STXcKRVFZRFZRUUtFd3ByZFdKbGNtNWxkR1Z6TUI0WERUSTJNREV4T0RBeE1UWTFObG9YRFRNMk1ERXhOakF4TVRZMQpObG93RlRFVE1CRUdBMVVFQ2hNS2EzVmlaWEp1WlhSbGN6QlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VICkEwSUFCQ0dTWUZHcjlLWTFnbzM4U2xVZlNzTG0rT3NwSkRuU2ZlMWYzd3N4ckZBdk14ZGRHQ2NQakhQZUlLRVEKNTJWdUx0d2owanJqb2lYTDI0dGJaUEpPSWZxallUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ2hEQWRCZ05WSFNVRQpGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFCkZnUVU4R0VlQnh4SUhqVys5T2xBdENOcy9uVzRDNXd3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQUk4ZGliQjIKZXI5ODFXbGgyV0plMldSQWdhMTIrZk83RFo2RlhkblgxMzA2QWlCLzJoeEdBS3dTTDdBVVhQN0NCakVzdTd1cQp0bjV2VFFUSzNsdU5lSFo1eXc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUlzY1VHb3BrM01XZGh2SlVvQm01eG1SVHNicWo1dlV0Smd5VWxqbFgxaTJvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFSVpKZ1VhdjBwaldDamZ4S1ZSOUt3dWI0Nnlra09kSjk3Vi9mQ3pHc1VDOHpGMTBZSncrTQpjOTRnb1JEblpXNHUzQ1BTT3VPaUpjdmJpMXRrOGs0aCtnPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
    aggregatorCA:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJYekNDQVFXZ0F3SUJBZ0lRTmV6bFkyZitjTjk3MTI2amI4cENJVEFLQmdncWhrak9QUVFEQWpBQU1CNFgKRFRJMk1ERXhPREF4TVRZMU5sb1hEVE0yTURFeE5qQXhNVFkxTmxvd0FEQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5QXdFSEEwSUFCRUFKZFA3U1FCdFd2T1RlV1ExZTFFS3hJeWsybDZBY0RsczNTNnA0bWdJeUJSQ1FsbHI1CjhVcXU0K2wzbXUrZzQxekYweTJjMElKU2lOZzJNTzkzOXpTallUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ2hEQWQKQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZApCZ05WSFE0RUZnUVVXY2dOSWM1SkdqbFFyMjYwclBxdHR3SVdJQll3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloCkFJR1RhSEpVbmlDdk9zOGtxV1dXNDQrL01pNCtUWTFHYkVOMndPZVRMOVgxQWlBU3N2NW01a01kOU9aR0tCTHkKQnd4QWpkUnhaYjVEdGRVT2pscXp5dGVzT1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUVCRlkrcVA0YVU5SVZuaDR5Qy9BRW42UDFTYmVaQ2NaWHoyUVd4dUp6b3FvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFUUFsMC90SkFHMWE4NU41WkRWN1VRckVqS1RhWG9Cd09XemRMcW5pYUFqSUZFSkNXV3ZueApTcTdqNlhlYTc2RGpYTVhUTFp6UWdsS0kyRFl3NzNmM05BPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
    serviceAccount:
        key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlKS1FJQkFBS0NBZ0VBdXFESUFYMW1vTUNHYXc5L3ZYNzVQcVZUelpDMXRxOEFrT0NQb2R4OWY4VitLam0rClNDQ3hmMmxoZWF6K2EyZUFmMkJ5Y1VMaEhhN3lST2JlUkN0OVFGaUk5a2NuL2JrTlRYZitQa043R0JGMzBtVkUKMy92WEVKSEFKYzI4THg4cXlKMmlyRVRKUm1CemlybDZhZDc1eWtGZitUejZZNy9LblNRcEJ4MkJac2hWc3hZdgpqeVdnUWF3WHcxdy9ZMjcrdzhWVHlCVEh2TzNBVmxQdXJLTXFycHBmQ0F4dWxyMm5lZjY3UHBjeUszRHpFeFVVClQ2RHFOOEpMYmt6Q1hNRmo0OFQ5L05sTVBCMXg1bTI1Z1NlV0V4YW83bFpRTGVNc3BIT3daQ3VtSG5iVW9qRDYKLzdpMERUZ2FVUWdUZlQ3VVpnR1pkcUl6Y21ocGpRNWdpNUpBZzlQZ25vM3gyZGY0NGRyNmdzVXZuYlMramY0NgpaUVY2eWJ2YWRUbHpuTkdWVGhadTMvL3ZNeW9sL3VGSTlSdFFlT0FmSjB4Y3pWRDNyWTNIcy9pQWtyb3EveFdUClU0MUs0YzROeDhsb2F3NWhoTHhZSTlTeWQ0T0k4UDZNeUJCYkhTZ05mNm9hV0JMQnJWNzlIc2RHUGlhSEFzQUkKQUpzWUlmTEo4ZFh3RndLQ0xhRkxEdjVCTlJjaUdocVU2K29xL0FPcWFaODFNVUlGZDVKeFpWT3NPNXh6Q0lXcgo0Tlc0STduVklubWluRnRBSmQ5OUF0UG0wb21wOHlHL210dGZ6UDk0TXYxNmFMRm5meXloL1g5NVoxRHJ1VXVPCmRyZlVzcUs4R0VyZ09uVGJtY2lpRHlGYkx3cDZraDFjbVRXL2dNckJab0xzMitzZG1GWStUd1JTNTlrQ0F3RUEKQVFLQ0FnQUh0aVVOaXJUMjUzMm1adG1NWnZhOWsrOUdpemcyK0R3NXdFMnZEb0ZSQ2tRUVVwcCtPSHVkSENtZQo4WHNCelNFT0lsb1lPLzg1VHNWTCs0NHJtdkJ0L0RxTWtwd2dhOGtVN21SZkJrTEwxOHp2c0tlTDZjZ1ZNekNSClgxTHJUNHBoQjhKMUE5S2RTZGI4WUhXaWNrZzRCME9EOVBVVHNoVVpNU2xRMWZORzMvaEtraHdjK2gwSkdhZFIKdHpvWFRiclJOQkltTGxXaWhPQnhzTDRuL0FZRGVQVjhTNmMySzFnRVBuWldPOEVpOG1QWTRnSVkyRGxWWEgzcApiTnFMSXFLU0FzM0w2TjZ4alRYcm81VUt0U3dLVmVGZEY4dndXWGE2eE4wQkJweXluWTVqdFVwcHpxUUI5OU4rCmphcmdmZndneXVnZ2NzdFZhdU1ScFFwd09mYllhWTZzUWdtbkZIbkR5N3FBSmcySTRtNG9JNVM0WWNtUU5UV3cKdEVRMm4zS3FoRnczUDh1L01YbENxWThtUlE4dHFuVFp6cCtwdURsSjVVbWo5RXlsQk1wTFYxVnB1ZDNoekx4awo5Y2xJMlFqUENlYkFybEJMLzNMdW5kZnJuS0tvUmRENWlHc0NyaGJPUXlsQnI2UmtzYkJrNXZFcjU4UUk3cjZDCnNjT2lGaXdkUWN4aHJPak5uUHJoQlAvTlZhbmlyc0lNd3U0Si9MMytpbzJlaFJtYkoxTjRsOTd1K2kwUHhuRWQKVUxxYlYydmExdVpOQTJYTFk2RDY3VVlRQysyR0lQNHJWbU5NL00vS21oMGJYd0JyUE14RG42cGVleDhvb1lZTwp2WEdNcVJzN0Y0c0xFbjJHL3lkUlQ5d3RmZktQQzZCQXI1cytRYUJtV1Vqa1JlODZBUUtDQVFFQXo5ZEhTUk9ICmxGbUpJSXF5am1RUXJBektFYWg3MCtYTXNzMEpKYklHODk0T0ZwRW5qaTNKaUFYMUNBVDYrdlU0clhpM0ozMVIKZldIS2NaVFhuUmN4bUNKRlpLaHo2czNJSmczdWVpbzZzWW1LbW5XOXZmRFpLSUhkZUZsTVQ2OUpISkxDbStTWgoxeGt5SEJkQzRDeW55dG9TUTd1L2Z1dWdUazJLbjlQQWhyY0dLblhiR2VZNHJ4REkyUTZTVTdLNEhxbXh1Qi90ClBzaUFkSEtXRGkwbzE4UlVsenN1NThzNUFvZGhIQnA4Vm0rVXl1aDFNeTUyQVppWHF2bjZYR0Nvb3lTM2orS2kKY084bktHMUpTT2owWXhjSGlNdVNLZmhDQm1pNktYeGZMYjFvSUxWa3gzQ2VROWp0RzFXMXZCaGY1Mm9PRkJKTQpNWHN2L1RtL09OdGVTUUtDQVFFQTVkOHlKT3lWdi9ORWk3Vm5DZ1ArZXByVmlFZ3RabFpvS2lZeXl4RVpmWXYwCjE0Wm9SeDdva3BRZFB0QklZYU0zdVdobCsrVWZra0xmMTJ2WG90TEJiRGJZaTJrU1g1aGJsVU5nR1ZYRFBVMHgKZG1zS2VuNFhZbEE5YktBLzlFTC9mR3pQRXhNS0lvOTl1T3cxRHZ4d1dPejZZVUVFNWJvK0VqTG9na1pUU2F2UwpsSTBISmt1Zk56Mi9yeHQrZ2I3eHh3K0MzdUNlSC9wN0NTNjdXZWRxYUl2cjlVcWNwaE5OZFF1YW52VUZ2RW04ClRsUG1WSExtQ2h6V2hpNmY3Z1ZnUHk1a3IrVmFGKytEVW9JVkFhVUk3MlA0R2V4SS80YWdNUTdtVHIxR3k5cmQKMHpWbUpDbnp5SzUxRCtDUm1LZktkMEtFc0VkS0VMdSt5RU12ZXZoOUVRS0NBUUEyQ2pOdXZMVXp6VlBxTWlYYgpBQW1Wc24yWHVjYjRnWGVIeGVmcTlTNzVtWEx3U3kyTnVqbjhOQkJSMVhtc1pyWWw1STA2cDByWTN1UlVRKzhMCjJVdjcwbTFZanJRVkNReFJXSzM0OWFIdEoyWHlZMHJDYUMwT2F6VzZaUDJDZW9EMy9QQzh0K09JR2ZUOWVNN2EKbXNIRjdJMXpMdzNMWWxoOEE0MVhvU2NkMzlpcWtabzJVYlhMVHdIcDdlLzk4eW9NVHZMMmZOYWl6RjhaNS9FOApIbUhRT0N3R1prejcxOHNxN1NoQ3RtQTkyU1ZHM01vY1ZLZzZJZ0xOWWRIRzB4c0YwRFlxSXpNNVNmVlVmWlhnCmJ6R2IwaEVUY0ZyQXJ0djc3cDc0eW0yMDV0cDhKcTNkYlZxNUtWMzlEWHdEUEJNemlFL0F5RUVuWEhCTjF3WHgKTXBpQkFvSUJBUURZK1lnM1dpa3ZlY3ZsbzJDVEQ1b1EyRDFkMmVNZ2ljYmdvaFdubjRoVC9Oc3E1RzloVWtkcwpzK20yOUpxZHJwWldwN2c3djlYQkZPWjhUQXJLWWV5NDNEd2h1eGZncThzbVpPWThnN3M2RGJiMmM2cjhYREJ1CldCYmloWkJZV3pVVW1SQU1qUmd2N3dsWWwzeXRuSkhmSGpCbnhCdC9UQUJ5NVNLYWRROEFwdktwelVSR1hYTDMKalkxMUY1cWRsVUphQnNZYzRoL2ZSMnNEQzkxRHl5K2haeEZlQXdOQnIwNlpnRTUrWkFENTdRK1ZUNVJGZWY2dwo1TytJMEZHZE5lM1hOVTlNeUV2MTg5b2M4elFvelVKVjFDTEhOVVRpREkwQVFYUWFOb2F3dlBKTS9rWmZORW9yCnpxQW9VR3lkanlPSTFueXdkMW50MllrSE5vT0dxeTVCQW9JQkFRQ1VZRTFNc3NUMVFFNno3YW15ZXJKek83TVgKbndHaitnanlHTDVoY1dMODR2QVJJb2VzZ1NqeHZWMnRaL2NsZEw0dkFva2NVSkE1N0UrRnk5Y3hHZ2tMclArMwpEYnUxMWFzL2E5cjQ1N2VyQ0ZCaysrK1dsbVZ0RzQwcGIvd2JxdzRvajVaVTgxMDJLWGltdnRUeFlqWHlKeHZOCll3eGxYeUVQVFRJdm83d3Z2NlMzRzhac1pMZTVIa1pTR2cyM3ZXTmZqTUpKV2paQjU5ckNyOElDbXdZUmNCalYKVitqVHY2ak50UmpWSW83dEZnUUZqcXNCdTJWV1g0ZUhTUUlYNFMrTCtHeTkrRXlMc2ErdTA3SmNkUE5vL3F6NwovbGxkL3NRUDdXRElGTC92NXltTWdvNmpObHlVd0hqd2FpcjhMWFB4cTlDNUozOENaUEtsbTZoeWRyUFAKLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0K
    apiServer:
        image: registry.k8s.io/kube-apiserver:v1.35.0
        admissionControl:
            - name: PodSecurity
              configuration:
                apiVersion: pod-security.admission.config.k8s.io/v1alpha1
                defaults:
                    audit: restricted
                    audit-version: latest
                    enforce: baseline
                    enforce-version: latest
                    warn: restricted
                    warn-version: latest
                exemptions:
                    namespaces:
                        - kube-system
                    runtimeClasses: []
                    usernames: []
                kind: PodSecurityConfiguration
        auditPolicy:
            apiVersion: audit.k8s.io/v1
            kind: Policy
            rules:
                - level: Metadata
    controllerManager:
        image: registry.k8s.io/kube-controller-manager:v1.35.0
    proxy:
        image: registry.k8s.io/kube-proxy:v1.35.0
    scheduler:
        image: registry.k8s.io/kube-scheduler:v1.35.0
    discovery:
        enabled: true
        registries:
            kubernetes:
                disabled: true
            service: {}
    etcd:
        ca:
            crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJmVENDQVNPZ0F3SUJBZ0lRTWtpMjlnNXFGTEM1MHMrUVQwaW5mekFLQmdncWhrak9QUVFEQWpBUE1RMHcKQ3dZRFZRUUtFd1JsZEdOa01CNFhEVEkyTURFeE9EQXhNVFkxTmxvWERUTTJNREV4TmpBeE1UWTFObG93RHpFTgpNQXNHQTFVRUNoTUVaWFJqWkRCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkRWS2tyMzlSMjFFCk03WXZqZm9ac3VWemhhKzV3MFU4NFlvY05Ub2tVdWQxZWcyMENnYjc3ZFpqbXdGRmh3S3Z6S0w5VzNjKzJoYW8KTjhJRy9oWGJVTlNqWVRCZk1BNEdBMVVkRHdFQi93UUVBd0lDaERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjRApBUVlJS3dZQkJRVUhBd0l3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVelZGTXkyN254cjRLCmRWczh4RFJINTByd094d3dDZ1lJS29aSXpqMEVBd0lEU0FBd1JRSWhBSitEOVJsNHBvTjdubWxmUGVoeHNuUkQKWGJsWlFrOGdvbkRMVVo3My80SW5BaUJtWU9aL0x3aXVRUldBQXZMa09naE1YYmNLdjRRL29DNVByalhnTDZjWApndz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
            key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSVAyY3hZMWNRdnBNUTVaeTNrOElTQ2xFNGttSkpudEVJeEhPRGRTM3UyTVdvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFTlVxU3ZmMUhiVVF6dGkrTitobXk1WE9GcjduRFJUemhpaHcxT2lSUzUzVjZEYlFLQnZ2dAoxbU9iQVVXSEFxL01vdjFiZHo3YUZxZzN3Z2IrRmR0UTFBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
---
apiVersion: v1alpha1
kind: HostnameConfig
auto: stable
---
apiVersion: v1alpha1
kind: Layer2VIPConfig
name: 10.2.0.10
link: enp0s2
